AllCops:
  Exclude:
    - "**/vendor/**/*"
    - "**/*.gemspec"
    - "spec/**"
  NewCops: enable
  TargetRubyVersion: 3.2.2
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false