AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0.2
  SuggestExtensions: false

Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false